"""Literal emitted-key fixtures for selected and HPO SynthCity contracts."""

SELECTED_SYNTHCITY_VARIABLE_COLUMNS = ("age", "target")
SELECTED_SYNTHCITY_ATTACK_TARGET_TYPES = {
    "secret": "categorical",
    "income": "continuous",
}

SELECTED_SYNTHCITY_EMITTED_KEY_FIXTURES = (
    (
        "sanity",
        "data_mismatch",
        ("sanity.data_mismatch.score",),
    ),
    (
        "sanity",
        "common_rows_proportion",
        ("sanity.common_rows_proportion.score",),
    ),
    (
        "sanity",
        "nearest_syn_neighbor_distance",
        ("sanity.nearest_syn_neighbor_distance.mean",),
    ),
    (
        "sanity",
        "close_values_probability",
        ("sanity.close_values_probability.score",),
    ),
    (
        "sanity",
        "distant_values_probability",
        ("sanity.distant_values_probability.score",),
    ),
    (
        "stats",
        "jensenshannon_dist",
        (
            "stats.jensenshannon_dist.marginal",
            "stats.jensenshannon_dist.source_table_macro_v2",
            "stats.jensenshannon_dist.max_variable_v2",
            "stats.jensenshannon_dist.variable_v2.age",
            "stats.jensenshannon_dist.variable_v2.target",
        ),
    ),
    (
        "stats",
        "chi_squared_test",
        ("stats.chi_squared_test.marginal",),
    ),
    (
        "stats",
        "inv_kl_divergence",
        ("stats.inv_kl_divergence.marginal",),
    ),
    (
        "stats",
        "ks_test",
        ("stats.ks_test.marginal",),
    ),
    (
        "stats",
        "max_mean_discrepancy",
        ("stats.max_mean_discrepancy.joint",),
    ),
    (
        "stats",
        "wasserstein_dist",
        ("stats.wasserstein_dist.joint",),
    ),
    (
        "stats",
        "prdc",
        (
            "stats.prdc.precision",
            "stats.prdc.recall",
            "stats.prdc.density",
            "stats.prdc.coverage",
        ),
    ),
    (
        "stats",
        "alpha_precision",
        (
            "stats.alpha_precision.delta_precision_alpha_OC",
            "stats.alpha_precision.delta_coverage_beta_OC",
            "stats.alpha_precision.authenticity_OC",
            "stats.alpha_precision.delta_precision_alpha_naive",
            "stats.alpha_precision.delta_coverage_beta_naive",
            "stats.alpha_precision.authenticity_naive",
        ),
    ),
    (
        "performance",
        "linear_model",
        (
            "performance.linear_model.gt",
            "performance.linear_model.syn_id",
            "performance.linear_model.syn_ood",
        ),
    ),
    (
        "performance",
        "mlp",
        (
            "performance.mlp.gt",
            "performance.mlp.syn_id",
            "performance.mlp.syn_ood",
        ),
    ),
    (
        "performance",
        "xgb",
        (
            "performance.xgb.gt",
            "performance.xgb.syn_id",
            "performance.xgb.syn_ood",
        ),
    ),
    (
        "performance",
        "feat_rank_distance",
        (
            "performance.feat_rank_distance.corr",
            "performance.feat_rank_distance.pvalue",
        ),
    ),
    (
        "performance",
        "linear_model_augmentation",
        (
            "performance.linear_model_augmentation.gt",
            "performance.linear_model_augmentation.aug_ood",
        ),
    ),
    (
        "performance",
        "mlp_augmentation",
        (
            "performance.mlp_augmentation.gt",
            "performance.mlp_augmentation.aug_ood",
        ),
    ),
    (
        "performance",
        "xgb_augmentation",
        (
            "performance.xgb_augmentation.gt",
            "performance.xgb_augmentation.aug_ood",
        ),
    ),
    (
        "detection",
        "detection_xgb",
        (
            "detection.detection_xgb.mean",
            "detection.detection_xgb.raw_auc",
            "detection.detection_xgb.effective_auc_v2",
        ),
    ),
    (
        "detection",
        "detection_mlp",
        (
            "detection.detection_mlp.mean",
            "detection.detection_mlp.raw_auc",
            "detection.detection_mlp.effective_auc_v2",
        ),
    ),
    (
        "detection",
        "detection_linear",
        (
            "detection.detection_linear.mean",
            "detection.detection_linear.raw_auc",
            "detection.detection_linear.effective_auc_v2",
        ),
    ),
    (
        "privacy",
        "delta-presence",
        ("privacy.delta-presence.score",),
    ),
    (
        "privacy",
        "k-anonymization",
        (
            "privacy.k-anonymization.gt",
            "privacy.k-anonymization.syn",
        ),
    ),
    (
        "privacy",
        "k-map",
        ("privacy.k-map.score",),
    ),
    (
        "privacy",
        "distinct l-diversity",
        (
            "privacy.distinct l-diversity.gt",
            "privacy.distinct l-diversity.syn",
        ),
    ),
    (
        "privacy",
        "identifiability_score",
        (
            "privacy.identifiability_score.score",
            "privacy.identifiability_score.score_OC",
            "privacy.identifiability_score.score_entropy_weighted",
            "privacy.identifiability_score.score_OC_entropy_weighted",
        ),
    ),
    (
        "privacy",
        "DomiasMIA_prior",
        (
            "privacy.DomiasMIA_prior.accuracy",
            "privacy.DomiasMIA_prior.aucroc",
            "privacy.DomiasMIA_prior.effective_auc_v2",
        ),
    ),
    (
        "attack",
        "data_leakage_mlp",
        (
            "attack.data_leakage_mlp.baseline_adjusted_advantage_v2",
            "attack.data_leakage_mlp.legacy_accuracy",
            "attack.data_leakage_mlp.mean",
            "attack.data_leakage_mlp.raw_accuracy.secret",
            "attack.data_leakage_mlp.majority_baseline.secret",
            "attack.data_leakage_mlp.chance_baseline.secret",
            "attack.data_leakage_mlp.balanced_accuracy.secret",
            "attack.data_leakage_mlp.macro_f1.secret",
            "attack.data_leakage_mlp.classification_score.secret",
            "attack.data_leakage_mlp.classification_baseline.secret",
            "attack.data_leakage_mlp.baseline_adjusted_advantage_v2.secret",
            "attack.data_leakage_mlp.n_eval.secret",
            "attack.data_leakage_mlp.uncertainty_v2.secret",
            "attack.data_leakage_mlp.normalized_mae_v2.income",
            "attack.data_leakage_mlp.disclosure_risk_v2.income",
            "attack.data_leakage_mlp.baseline_mae.income",
            "attack.data_leakage_mlp.n_eval.income",
            "attack.data_leakage_mlp.uncertainty_v2.income",
        ),
    ),
    (
        "attack",
        "data_leakage_xgb",
        (
            "attack.data_leakage_xgb.baseline_adjusted_advantage_v2",
            "attack.data_leakage_xgb.legacy_accuracy",
            "attack.data_leakage_xgb.mean",
            "attack.data_leakage_xgb.raw_accuracy.secret",
            "attack.data_leakage_xgb.majority_baseline.secret",
            "attack.data_leakage_xgb.chance_baseline.secret",
            "attack.data_leakage_xgb.balanced_accuracy.secret",
            "attack.data_leakage_xgb.macro_f1.secret",
            "attack.data_leakage_xgb.classification_score.secret",
            "attack.data_leakage_xgb.classification_baseline.secret",
            "attack.data_leakage_xgb.baseline_adjusted_advantage_v2.secret",
            "attack.data_leakage_xgb.n_eval.secret",
            "attack.data_leakage_xgb.uncertainty_v2.secret",
            "attack.data_leakage_xgb.normalized_mae_v2.income",
            "attack.data_leakage_xgb.disclosure_risk_v2.income",
            "attack.data_leakage_xgb.baseline_mae.income",
            "attack.data_leakage_xgb.n_eval.income",
            "attack.data_leakage_xgb.uncertainty_v2.income",
        ),
    ),
    (
        "attack",
        "data_leakage_linear",
        (
            "attack.data_leakage_linear.baseline_adjusted_advantage_v2",
            "attack.data_leakage_linear.legacy_accuracy",
            "attack.data_leakage_linear.mean",
            "attack.data_leakage_linear.raw_accuracy.secret",
            "attack.data_leakage_linear.majority_baseline.secret",
            "attack.data_leakage_linear.chance_baseline.secret",
            "attack.data_leakage_linear.balanced_accuracy.secret",
            "attack.data_leakage_linear.macro_f1.secret",
            "attack.data_leakage_linear.classification_score.secret",
            "attack.data_leakage_linear.classification_baseline.secret",
            "attack.data_leakage_linear.baseline_adjusted_advantage_v2.secret",
            "attack.data_leakage_linear.n_eval.secret",
            "attack.data_leakage_linear.uncertainty_v2.secret",
            "attack.data_leakage_linear.normalized_mae_v2.income",
            "attack.data_leakage_linear.disclosure_risk_v2.income",
            "attack.data_leakage_linear.baseline_mae.income",
            "attack.data_leakage_linear.n_eval.income",
            "attack.data_leakage_linear.uncertainty_v2.income",
        ),
    ),
)

HPO_SYNTHCITY_EMITTED_KEY_FIXTURES = (
    (
        "sanity.nearest_syn_neighbor_distance",
        {"sanity": ["nearest_syn_neighbor_distance"]},
        ("sanity.nearest_syn_neighbor_distance.mean",),
    ),
    (
        "stats.wasserstein_dist",
        {"stats": ["wasserstein_dist"]},
        ("stats.wasserstein_dist.joint",),
    ),
    (
        "stats.inv_kl_divergence",
        {"stats": ["inv_kl_divergence"]},
        ("stats.inv_kl_divergence.marginal",),
    ),
    (
        "performance.xgb",
        {"performance": ["xgb"]},
        (
            "performance.xgb.gt",
            "performance.xgb.syn_id",
            "performance.xgb.syn_ood",
        ),
    ),
    (
        "default",
        {
            "stats": ["wasserstein_dist", "inv_kl_divergence"],
            "sanity": ["nearest_syn_neighbor_distance"],
            "performance": ["xgb"],
        },
        (
            "stats.wasserstein_dist.joint",
            "stats.inv_kl_divergence.marginal",
            "sanity.nearest_syn_neighbor_distance.mean",
            "performance.xgb.gt",
            "performance.xgb.syn_id",
            "performance.xgb.syn_ood",
        ),
    ),
)
